# Generated by Django 2.2.6 on 2019-10-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
